name: Get GitHub TAR
on:
  push:
    tags:
      - '*'
jobs:
  download-tar:
    runs-on: ubuntu-latest
    steps:
      - name: Download GitHub-generated TAR
        run: |
          # El nombre del tag está en `github.ref_name`, 
          # y el repo en `github.repository` 
          wget -O source.tar.gz \
            "https://github.com/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"

      - name: Checksum
        run: sha256sum source.tar.gz > checksum.txt

